### ISSUE TITLE
openconfig-network-instance: incorrect constraints

### ISSUE THREAD

**Issue by andaru** [openconfig/public#115]
The `openconfig-network-instance.yang` module (at head) has two constraints which are impossible to satisfy:

https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-network-instance.yang#L549

and
https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-network-instance.yang#L557

Both of these `uses` statements have `when` constraints which require the `../config/type` identityref leaf to be the `DEFAULT` value.  However there is no such enumeration defined for the identityref's base, so the `when` constraint can never be satisfied.  Tools which follow the schema will consider the `mpls-top` or `sr-top` uses to be invalid, and do produce errors about unexpected child nodes of `network-instance`. 

Suggested fix:

I believe these should both be `when "../config/type = 'DEFAULT_INSTANCE'";`, which is of the required `ENDPOINT_TYPE` enumerate.

**Comment by robshakir** [comment]
Thanks for catching this -- I think this is right. The value should be `DEFAULT_INSTANCE` but it's the `NETWORK_INSTANCE_TYPE` identity that needs to be matched, since the leaf it intends to match is [this one](https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-network-instance.yang#L897).

I'll submit a fix now - will be merged post-review.

**Comment by andaru** [comment]
Thanks Rob - and yes, I had searched for the first `leaf type` in the model.  I agree the correct base identity is `NETWORK_INSTANCE_TYPE`.

**Comment by aashaikh** [comment]
This should be fixed in the latest published model. Please re-open if it isn't resolved.
