### ISSUE TITLE
OC rolling window statistics - instance timestamp

### ISSUE THREAD

**Issue by jli75024** [openconfig/public#1213]
Hi,

What is the best time to capture the instant value within the context of following grouping.  At end of the rolling window or current time?

grouping avg-min-max-instant-stats-precision2-dB {
    description
      "Common grouping for recording dB values with 2 decimal
      precision. Values include the instantaneous, average,
      minimum, and maximum statistics.  Statistics are computed
      and reported based on a moving time interval (e.g., the last
      30s).  If supported by the device, the time interval over which
      the statistics are computed, and the times at which the minimum
      and maximum values occurred, are also reported.";

    leaf instant {
      type decimal64 {
        fraction-digits 2;
      }
      units dB;
      description
        "The instantaneous value of the statistic.";
    }

    leaf avg {
      type decimal64 {
        fraction-digits 2;
      }
      units dB;
      description
        "The arithmetic mean value of the statistic over the
        time interval.";
    }

    leaf min {
      type decimal64 {
        fraction-digits 2;
      }
      units dB;
      description
        "The minimum value of the statistic over the time interval.";
    }

    leaf max {
      type decimal64 {
        fraction-digits 2;
      }
      units dB;
      description
        "The maximum value of the statistic over the time
        interval.";
    }

    uses stat-interval-state;
    uses min-max-time;
  }

**Comment by dplore** [comment]
In practice, the specific details of how the instant value is obtained are implementation dependent.  

If you are looking for a recommendation for your implementation, IMO, instant should fetch whatever the device has cached as the 'current' or 'latest' value.  Updating of that cache should probably be done whenever your implementation reads from the hardware.  If in your window (say 300 seconds) the hardware is sampled every 60 seconds, then the 'instant' value should contain the most recent sample.  (therefore the instant value might be up to 60 seconds old)

Of course, your implementation has more freedom than this.  You could refresh the cache by sampling the hardware if the cache is stale at the time the data is attempted to be read.   

In any scenario, I suspect you always want to have some kind of cache vs. directly sampling the hardware because gnmi get/subscribe requests may be far higher than what is efficient to sample from the hardware.

**Comment by jli75024** [comment]
Thanks!
