### ISSUE TITLE
Regex patterns should not be anchored explicitly

### ISSUE THREAD

**Issue by jeroen-dhollander** [openconfig/public#122]
Hey,

In the openconfig models, the regex patterns are usually anchored (i.e. they start with `<` and end with `$`).

For example [openconfig-yang-types.yang](https://github.com/openconfig/public/blob/master/release/models/types/openconfig-yang-types.yang) contains this:
```
  typedef dotted-quad {
    type string {
      pattern '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|'       +
              '25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4]' +
              '[0-9]|25[0-5])$';
    }
    description
      "An unsigned 32-bit integer expressed as a dotted quad. The
      format is four octets written as decimal numbers separated
      with a period character.";
  }
```

However, the YANG spec uses the [w3 xmlschema](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/), which anchors everything implicitly,
and also does not prescribe any special meaning to the `$` character.
This is explicitly mentioned in [this section](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#regexs).

This means that for example the `typedef dotted-quad` above actually matches `^1.2.3.4$` and not `1.2.3.4`.

This is causing issues when using openconfig models with other tools that check and enforce the patterns, like libyang (see https://github.com/CESNET/libyang/issues/422 ).

With regards,

Jeroen

**Comment by aashaikh** [comment]
Thanks for noting this -- it's been raised before, and our plan is to create an extension definition for the regex patterns defined in OpenConfig (e.g., `posix-regex-pattern` or something similar).  This would prevent other tools from failing trying to interpret the `pattern` statement according to W3C rules per the language spec.   We do not have any plans at the moment to rewrite the OC patterns as W3C, however, since the original motivation (lack of widely available tooling for this standard) still applies.

Please feel free to reopen if you have questions / comments.
