### ISSUE TITLE
Is the type of network instance by default set as DEFAULT_INSTANCE under config of network instance list

### ISSUE THREAD

**Issue by sunseawq** [openconfig/public#148]
Is the type of network instance by default set as DEFAULT_INSTANCE under config of network instance list?
     leaf type { 
       type identityref { 
         base "oc-ni-types:NETWORK_INSTANCE_TYPE"; 
       } 
       description 
         "The type of network instance. The value of this leaf 
         indicates the type of forwarding entries that should be 
         supported by this network instance"; 
     } 
Why not add default statement after the leaf 'type' if the answer is yes?
Also it is not clear to me whether NETWORK_INSTANCE_TYPE is by default set as global routing instance for a network device? Can we set the default value of NETWORK_INSTANCE_TYPE as L3VRF?
   identity DEFAULT_INSTANCE { 
     base NETWORK_INSTANCE_TYPE; 
     description 
       "A special routing instance which acts as the 'default' or 
       'global' routing instance for a network device."; 
   } 
It is confusing to say the 'default' or 'global' routing instance can be both viewed as DEFAULT_INSTANCE?

**Comment by robshakir** [comment]
Please try and open only one issue per discussion. There are three that look very similar here. This makes conversation and discussion more coherent.

A new network instance should not be default "DEFAULT_INSTANCE", since there can only be one per system. We prefer the approach that the type must be explicitly set, therefore there is no default for the `type` leaf.

I don't see a good argument to make any type a default -- configuration is relevant to a specific type of instance - and hence config generation should explicitly set it as it creates a new network instance in the list.
