### ISSUE TITLE
Violation of prefix rules for mpls models

### ISSUE THREAD

**Issue by miott** [openconfig/public#164]
Bouncing along the chain of dependencies when loading openconfig models, we discovered that these mpls models assign openconfig-yang-types a prefix of "yang".
```
openconfig-mpls-rsvp.yang:  import openconfig-yang-types { prefix yang; }
openconfig-mpls-te.yang:  import openconfig-yang-types { prefix yang; }
```
Along that some line of model dependencies, ietf-yang-types.yang is imported and also is assigned a prefix of "yang".
```
openconfig-network-instance.yang:  import ietf-yang-types { prefix "yang"; }
```
I believe the mpls files meant to assign prefix "oc-yang" to openconfig-yang-types.  This has caused some issues with our tooling.

**Comment by robshakir** [comment]
This is not a bug -- your tooling should be able to handle this There is no
"rule" that the same import prefix must be used consistently across models,
since import prefixes are in the context of a particular module.

What tooling are you using that is unable to handle this?

Kind regards,
r.

**Comment by miott7** [comment]
A little vague but, https://tools.ietf.org/html/rfc6020#section-7.1.4:
```
All prefixes, including the prefix for the module itself MUST be
unique within the module or submodule.
```
If a module which uses grouping, imports a module that imports another module etc... and some of the groups being used have duplicate prefixes, I would say that the modules using the grouping could end up with conflicting prefixes.

Another more specific example of prefix collision, including submodules in openconfig-mpls:
```
  // import some basic types
  import openconfig-mpls-types { prefix oc-mplst; }
  import openconfig-mpls-rsvp { prefix oc-rsvp; }
  import openconfig-mpls-ldp { prefix oc-ldp; }
  import openconfig-types { prefix oc-types; }
  import openconfig-interfaces { prefix oc-if; }
  import openconfig-extensions { prefix oc-ext; }
  import openconfig-segment-routing { prefix oc-sr; }

  // include submodules
  include openconfig-mpls-te;
  include openconfig-mpls-igp;
  include openconfig-mpls-static;
```
The import for openconfig-types sets the prefix to oc-types, but, with the openconfig-mpls-te submodule included, which is basically becoming part of openconfig-mpls, results in openconfig-mpls now having 2 prefixes for openconfig-types defined as the same in module.

Our tooling is looking for conflicting prefixes when a module is evaluated along with it's dependencies and issues warnings, then moves on.  We added the check because users have a tendency to dump a bunch of arbitrary models into our tool for exploration.

At this point, it looks like the models with conflicting prefixes, for example, ietf-inet-types and openconfig-inet-types, are close enough in content that regardless of which module definition is actually used, it still works.  It just seems like a recipe for trouble.

**Comment by jsterne** [comment]
Hi guys - didn't the module & submodule scoping rules change with YANG 1.1 ? Doesn't that make the scope of the prefix name expand to include the entire set of sub-modules + the parent module ?

**Comment by robshakir** [comment]
Jason,

The change in 1.1 didn't change the `import` scope, just the `include` one:

```

   o  For a module or submodule to reference definitions in an external
      module, the external module MUST be imported.

```


Cheers,

r.

**Comment by robshakir** [comment]
Jason,

The change in 1.1 didn't change the `import` scope, just the `include` one:

```
   o  For a module or submodule to reference definitions in an external
      module, the external module MUST be imported.
```

Taken from [7950](https://tools.ietf.org/html/rfc7950).

Cheers,
r.
