### ISSUE TITLE
route-distinguisher 2 byte number regex

### ISSUE THREAD

**Issue by abhishek4986** [openconfig/public#183]
The pattern for <2-byte assigned number> pattern seems incorrect. As an example, it doesn't accept a value of "10000" or "64535". Also, it accepts 2 digits values starting from 0 as in "08".

**Comment by gmuloc** [comment]
Agree with this analysis:

The regex at
https://github.com/openconfig/public/blob/master/release/models/network-instance/openconfig-network-instance-types.yang#L247

type 0 should be ASN<2bytes>:Assigned Number subfield<4bytes> (https://tools.ietf.org/html/rfc4364#section-4.2) - the 2 bits ASN values are indeed all the range: https://en.wikipedia.org/wiki/Autonomous_system_(Internet)


currenlty the regex will match for the ASN
* 65000 to 65000 and then missing for example 65529 which is  for 65[0-5][0-3][0-5] - missing all 60000 to 64999
* 11000 to 15999, 21000 to 25999, 31000 to 35999, 41000 to 45999, 51000 to 55999 for [1-5][1-5][0-9][0-9][0-9]
* 00 to 99, 100 to 999, 1100 to 1999, 2100 to 2999, ... and so on  for [1-9]?[1-9]?[0-9][0-9] which means missing all the number match [1-9]0[0-9][0-9] - that is you cannot be AS 1000 for example.
* 1 to 9 for [1-9]

The second part of the regex has the same issue as it won't allow the full range 0-(2^32-1) - e.g 4009000000 because of the fixed [0-4] in 3rd position.

**Comment by wenovus** [comment]
Thanks again for bringing this up, https://github.com/openconfig/public/commit/225dac979c4f98d210d9104bd70e7d236feed1be fixes the regex with some attached tests at https://github.com/openconfig/public/commit/624655d053ad1fdda62901c7e2055c22cd5d6a05.
