### ISSUE TITLE
Incomplete path for "when" statement of open-config-platform-port yang file and missing leaf called "type" inside "state" container of the same yang file

### ISSUE THREAD

**Issue by Nshet** [openconfig/public#187]
[openconfig-platform-port.txt](https://github.com/openconfig/public/files/2500604/openconfig-platform-port.txt)

the problem and the corresponding solution associated with it will be present in the attached ppt :
[correction ocpp.pptx](https://github.com/openconfig/public/files/2500606/correction.ocpp.pptx)

please, do check it quickly and resolve it as soon as possible.

**Comment by aashaikh** [comment]
Yes, there is an issue with the path -- it needs to be properly prefixed and corrected.  Note that your proposed update is actually incorrect since the component type leaf that is checked by the `when` statement is at the top-level, i.e., `/components/component/state/type`.  Thanks for pointing it out -- we'll get a fix pushed for this.

**Comment by Nshet** [comment]
Thank you Anees for considering the request . I would like to ask you that , when can we expect this changes will reflect? . The reason that I have asked you this question is that, we have release on January. It would be grateful that  it will  get fix  before January.

**Comment by aashaikh** [comment]
This fix has been merged and just needs to be published.  We'll try to push all the recent fixes this week.  thanks again.
