### ISSUE TITLE
Openconfig platform types doesn't have Identityref called OPTICAL_CHANNEL

### ISSUE THREAD

**Issue by Nshet** [openconfig/public#209]
Hi,
In, openconfig terminal device a part Is augmenting to the openconfig platform yang which expects openconfig platform types should have OPTICAL_CHANNEL idref inside it but the current openconfig platform types doesn't had it . please take a look in to the issue.
Augmentation part in Terminal device is as below:-
 // augment statements

  augment "/oc-platform:components/oc-platform:component" {
    when  "current()/oc-platform:state/oc-platform:type = 'OPTICAL_CHANNEL'" {
      description
        "Augment is active when component is of type
        OPTICAL_CHANNEL";
    }
    description
      "Adding optical channel data to physical inventory";

**Comment by vprasad** [comment]
Hi ,
Can anyone please look into this issue.
We are augment based on platform type as OPTICAL_CHANNEL.
but the identity OPTICAL_CHANNEL is not defined in openconfig-platform-types.yang.
Thanks,
Vivek prasad

**Comment by aashaikh** [comment]
I can't reproduce the issue (are you getting a compilation/validation error?).

The `OPTICAL_CHANNEL` identity is defined in the `openconfig-transport-types` module, which is included by the terminal device model.  I was able to verify that both pyang and confd are able to compile the terminal device model.

Please comment if you are still seeing issues.

**Comment by einarnn** [comment]
@aashaikh,

I just did a little experimentation with both confdc and pyang and discovered that neither currently implement proper validation of the identity value in a `when` statement comparison. Since the transport types yang module is imported, it definitely needs a prefix to disambiguate it with respect to any other module potentially defining its own `OPTICAL_CHANNEL`.

You can see that the prefix is needed if you define a couple of "canary" identities in the terminal device yang file, like this:

```
  leaf canary-one {
    type identityref {
        base oc-opt-types:OPTICAL_CHANNEL;
    }
    description
      "Canary 1";
  }

  leaf canary-two {
    type identityref {
        base OPTICAL_CHANNEL;
    }
    description
      "Canary 2";
  }
```

Using pyang then errors out on the `leaf canary-two`:

```
(pyang) $ pyang --lint openconfig-platform.yang openconfig-terminal-device.yang
openconfig-terminal-device.yang:1391: error: identity "OPTICAL_CHANNEL" not found in module openconfig-terminal-device
```

Or with confdc:

```
$ confdc -c --yangpath /opt/git-repos/clean-yang/standard/ietf/RFC openconfig-terminal-device.yang
openconfig-terminal-device.yang:1391: error: identity 'OPTICAL_CHANNEL' not found
```

Cold be that issues need to be raised with both pyang and confdc.

Cheers,

Einar

**Comment by aashaikh** [comment]
Thanks Einar -- probably not surprising that the `when` validation in both tools is not strong.  We can add an prefix to the reference in the `when` statement per your suggestion.

**Comment by vprasad** [comment]
Hi ,
We also were not getting any issues while compiling the openconfig-terminal-device.yang using confd compiled.
However during run time confd was not able to populate these augmented attributes because the prefix was not used with the OPTICAL_CHANNEL.
Similar issue we are facing in other yangs also .Plz correct those also.Ticket :-206 .

Thanks,
Vivek prasad
