### ISSUE TITLE
Shouldn't submodules to openconfig-aaa share same openconfig-version?

### ISSUE THREAD

**Issue by cho-m** [openconfig/public#217]
The current repo includes:

| Name | openconfig-version | module/submodule |
| --- | --- | --- |
| openconfig-aaa  | 0.4.1 | module |
| openconfig-aaa-radius | 0.3.1 | submodule |
| openconfig-aaa-tacacs | 0.3.1 | submodule |

According to openconfig-version extension in openconfig-extensions.yang (https://github.com/openconfig/public/blob/master/release/models/openconfig-extensions.yang#L61):

      Where several modules are used to build up a single block of
      functionality, the same module version is specified across each
      file that makes up the module.

I believe other cases of module/submodule(s) has their semantic version updated simultaneously in one commit.

It looks like this was the case until https://github.com/openconfig/public/commit/06b33ff792b5533081680e637c3243749c0bee5a where openconfig-aaa was updated but tacacs/radius were not.

**Comment by aashaikh** [comment]
We have been allowing module versions to evolve independently for some time.   You're correct that earlier we did keep module revisions in sync for "related" modules, which mostly boiled down to modules in the same subdir.  Going forward we will only update the revision/version of a *module* when there is a change in that module.

However, since a submodule should share the same YANG `revision` as the parent module (per RFC 6087 guidance), its openconfig-version should also be the same (we reflect the openconfig-version in the `reference` substatement of the `revision` statement).

We will clarify the description in the openconfig-extensions file -- thanks for spotting it.

**Comment by aashaikh** [comment]
This has been fixed in the latest set of published models.
