### ISSUE TITLE
OSC interface type

### ISSUE THREAD

**Issue by cpeng90** [openconfig/public#257]
Hi,

Just wondering whether we can add a new interface type IF_OSC for optical supervisory channel in openconfig-if-types.yang?

  identity IF_OSC {
    base INTERFACE_TYPE;
    description
      " Optical supervisory channel interface";
  }

Regards,
Cheng

**Comment by aashaikh** [comment]
@ejbrever FYI

My understanding is that the OSC is typically just an Ethernet interface on which some IGP might be running to implement the OSC.  I'm not sure a new interface type is justified here.  Are you looking for some way to indicate that a particular Ethernet interface is being used for the OSC?

**Comment by cpeng90** [comment]
Yes, I am looking for a way to indicate that the Ethernet interface is being used for the OSC instead of the RJ45. I think we can still use the interface name to distinguish whether it is for OSC but that would lock the name into a particular naming convention so that it can be distinguished from the rest interfaces. From operator perspective, would you prefer to using the naming convention or introducing a new type?

**Comment by ejbrever** [comment]
In the model, the the interface would be a leaf in the OSC config:
https://github.com/openconfig/public/blob/master/release/models/optical-transport/openconfig-transport-line-common.yang#L108

Would this help to identify that its use case is OSC?

**Comment by cpeng90** [comment]
I would think there should be a reference from openconfig-interface to openconfig-transport-line. no?

**Comment by aashaikh** [comment]
The alternative modeling could have been to augment such a reference into the interfaces model from the OSC model in `openconfig-transport-line-common`.  We would not want to put such a reference in the base interfaces model since its use is specific to the interfaces on a line system device.

The current modeling does allow you to make the association between OSC and corresponding interfaces as ejbrever pointed out.  Does this not work for your use case?  We could consider adding a reverse reference in addition (as described above), but we've tried to stay away from this pattern to avoid having the device need to keep these multiple values in sync

**Comment by cpeng90** [comment]
Thank you for clarification and I think we are in good shape now.
