### ISSUE TITLE
Clarification on terminal-device model error handing

### ISSUE THREAD

**Issue by prmanna** [openconfig/public#282]
Hi,

In openconfig-terminal-device.yang, the logical-channel can be of type ETHERNET or OTN (defined by logical-channel-type).

Question is:
A logical channel of type ETHERNET can accept the OTN config like tti-msg-transmit, tti-msg-expected etc. But the config will not be applied. 
Ideally it should not reject the config.
Is the assumption correct?

Regards,
Prasenjit

**Comment by ejbrever** [comment]
Hi Prasenjit, the "when" statements here should specify which container (otn or ethernet) to use based on the logical-channel-type:

https://github.com/openconfig/public/blob/master/release/models/optical-transport/openconfig-terminal-device.yang#L996

If it was specified in the config, it would be expected that the device would reject it as invalid since it doesn't conform to the "when" statements. If it just ignored the config, that might be fine, but probably has the potential to cause confusion from users as things they specified are ignored without informing them.

**Comment by prmanna** [comment]
Thanks Eric. This is clear now.
