### ISSUE TITLE
QSFP_PLUS missing in TRANSCEIVER_FORM_FACTOR_TYPE

### ISSUE THREAD

**Issue by prmanna** [openconfig/public#31]
Hi,

Checked in openconfig-transport-types.yang. QSFP_PLUS is missing. 
Any reason for this ?

Thanks,
Prasenjit

**Comment by aashaikh** [comment]
hi Prasenjit, we use QSFP / QSFP+ interchangeably in the models, esp. since in practice people primarily deploy QSFP+.

I think we can add QSFP_PLUS to be more precise if it's useful -- alternative would be to add some text to the description to make the usage clearer.

thanks for pointing it out.
-- Anees

**Comment by prmanna** [comment]
Thanks Anees.
