### ISSUE TITLE
pyang report a error ,what is wrong ? anyone know this problem  ?

### ISSUE THREAD

**Issue by zhanggongc** [openconfig/public#328]
root@debian:/home/cailei/openconfig/public/release/models/acl# pyang --plugindir $PYBINDPLUGIN -f pybind -o openconfig_acl.py openconfig-acl.yang
no format specified
root@debian:/home/cailei/openconfig/public/release/models/acl# 

"no format specified"   ??
![image](https://user-images.githubusercontent.com/58503468/74710148-e5da1e00-525b-11ea-9c80-b6ee7894d2e1.png)

**Comment by aashaikh** [comment]
This should probably be discussed in the [pyangbind](https://github.com/robshakir/pyangbind) repo since it is unrelated to models.

I was able to generate the python classes using the following (in a virtualenv):
```
pyang --plugindir $PYBINDPLUGIN -f pybind -o openconfig_acl.py ./openconfig/public/release/models/acl/openconfig-acl.yang -p ./openconfig/public/release/
```

I could not reproduce the `no format specified` error, but did have to add search paths to pyang with `-p`

**Comment by zhanggongc** [comment]
thanks for your comment.
In my virtual linux env ,still report "no format specified"

![image](https://user-images.githubusercontent.com/58503468/74718285-e0390400-526c-11ea-8902-9ecc14fdec39.png)
 "-f pybind" cannot be used  
so i also write a issue in the pyangbind repo .
