### ISSUE TITLE
Interface mapping to multiple network-instances

### ISSUE THREAD

**Issue by AndreasVoellmy** [openconfig/public#336]
The structure here https://github.com/openconfig/public/blob/22ecbc727e6b26c35646f90494304a63b725bc25/release/models/network-instance/openconfig-network-instance.yang#L377
suggests that a single interface might be associated with multiple network-instances. Is that the intent? What situations lead to that happening?

**Comment by robshakir** [comment]
Can you explain why that's the case? I don't think that we envisage that to be a scenario that is supported.

**Comment by AndreasVoellmy** [comment]
It seems that way to me, since there is not any constraint that enforces that each network instance has a disjoint set of interfaces. In other words it seems like the following would be legal according to the schema:

- network-instances
  - network-instance
    - config
      - name: "a"
    - interfaces
      - interface
        - config
           - interface: "eth1/2"
           - interface: "eth1/3"
  - network-instance
    - config
      - name: "b"
    - interfaces
      - interface
        - config
           - interface: "eth1/2"
           - interface: "eth1/4"

The important part of this example is that "eth1/2" appears in both the network-instance "a" and network-instance "b".

So would this be allowed? 

If it is allowed, then does this serve a useful purpose? Is there some situation where this is useful?

If not, what prevents it from being allowed by the schema?

To be clear, I don't know why one would want to allow this, that is why I was asking. But maybe there are some reasons for it.

**Comment by exa-arrcus** [comment]
There are many cases across data-models where constraints as such might be better left to backend validation.  Data-model constraints can very quickly become cumbersome, expensive and hard to maintain thus an implementation can always prevent the above scenario in the backend rather.

**Comment by robshakir** [comment]
Ebben's comment is right on here -- there are many places where the data model permits something that might not be supported by an implementation (and arguably should not be) -- e.g., two interfaces with the same address, two BGP instances with the same ASN etc. The complexity of describing all these limitations in the data model leaves to significant expense in processing, and begs the question of where one stops with these descriptions (e.g., platform X does Y, but Z doesn't -- how do you encode that in the model?). Given that this is the case, a client must be prepared for the case that the backend returns an error, and thus, this lets us choose a balance of the cost/benefit of describing these constraints in the models.

It should be noted that there might be cases where there is a need for an interface to be part of >1 network instance, consider half-duplex VRF for example.

**Comment by robshakir** [comment]
I feel this is also relevant to #333 that you opened too -- we don't have any `must` constraints today, and don't plan to add them.

**Comment by AndreasVoellmy** [comment]
Thanks for the replies. So I take it that the answer is: yes, the current data model allows a single interface to appear under multiple network interfaces, and there might be some case where this is useful - I'll look into your suggestion on half-duplex VRF.

Regarding the model and constraints. I think in this case, if it were desired, the model could have ensured that an interface appears under at most one network instance without must constraints, just be organizing data a bit differently. For example, instead of having a list of interface names under network-instance, there could be a network-instance name under each interface. That way, network-instances are located in one place, and each interface is associated with at most one network-instance. 

Interesting comments on the difficulty of maintaining models with must constraints and processing these constraints. I think the flip side is for consumers of the data. Generally speaking, knowing what constraints are expected to hold makes it easier to write a correct query against this data. In this case, it seems like a a different organization rather than additional constraints could have solved it just as well.

**Comment by robshakir** [comment]
There are, of course, different modelling approaches that can be taken. In the OpenConfig models, one of the principles that we have tried to follow is that we don't want to overload the "interface" construct. In the model where one assigns an interface to some other entity (network instance, protocol, etc.) under the interface itself -- then quickly, the interface construct becomes difficult to parse.

Along with avoiding overloading the interface -- we also wanted to try and stick with an operational workflow that made sense to the operators that were involved in the model development. In this context, we considered it more logical to start with the thing that was being debugged (a particular protocol, for instance) and then think about that interface within that context, rather than starting with the interface and working from there. Both are possible models, but this was the consensus at the time.

In terms of the constraints -- yes, to some extent more descriptive models help this, but only when there are constraints that are common across all platforms. If one over-fits the constraints then this means the model becomes too constrained to one use case -- e.g., it works for a router but not a ROADM, which hurts general compatibility. As with all these decisions, it's a trade off.

**Comment by AndreasVoellmy** [comment]
Makes sense. I think my suggestion did not need to have the mapping from interface-to-network-instance be under interface hierarchy. The key part would just be to have a list of interfaces where each interface can be assigned to at most one network-instance. Where exactly that listing lives doesn't matter that much - that could live under network-instances (but not under each network-instance). The point is just to model that this is a (partial) function from interface to network instances. But of course, this is all moot since it seems that the intent was to allow an interface to be assigned to multiple network-instances.

Definitely would not want to add constraints that aren't valid.

Thanks for the clarification. I think we can close this issue now, since the original questions have all been answered.
