### ISSUE TITLE
Clarification Multicast PIM yang

### ISSUE THREAD

**Issue by mhampasagar** [openconfig/public#353]
Hi ,
I have few queries in PIM YANG model
- there is sources-joined container , could some one explain more on what exactly this will be used for
- Only I see support for v4, how about V6,  if we want to extent this  fir v6, what is best way? introduce pimv6 container similar to pim. it would have been nice if its done like BGP with address family as many attributes will be common fro PIM v4 and V6.
- For PIM I do not see any state container to get routes from PIM protocol, any plans to add it. or its ok to add it similar to BGP like rib state container?
- Similar to unicast routes in AFT container, this can be extended for getting multicast route like ipv4-multicast and ipv6-multicast?

Thanks.

**Comment by chrisy** [comment]
The multicast implementation was bare-bones, just enough to support an immediate need at the time. I do not know of any plans among contributors to extend for IPv6, AFT or protocol state information, but patches are welcome.

I agree that refactoring for common support would be desirable, if possible, but sadly have no visibility of IPv6 PIM to be able to gauge the viability.

**Comment by mhampasagar** [comment]
Thanks @chrisy for the reply, So your suggestion is to add IPv6 if needed, also we can group common attributes for v4 and v6.
If we add V6 then instead of BGP like  with address family, it will be separate container similar to pim?

**Comment by chrisy** [comment]
@mhampasagar  Whatever makes the most sense, really.

The AF approach seems logical when there's a lot of common structure and the way the protocols work is somewhat tied; with BGP for example the transport is somewhat independent of the data carried - an IPv4 session can carry IPv6 reachability.

I do not believe this is so for PIM. In other protocols where this is also the case, like OSPFv2 vs v3 we've been working to bring together the common options to use a common grouping, but keep them otherwise independent in the resulting structure for a similar reason - in reality, they're different protocols with much in common. Does that also hold true for PIM in IPv4 and IPv6?

**Comment by mhampasagar** [comment]
@chrisy , from BGP session point of view , agree it make sense to for BGP with AF. PIM does not have anything similar where it carried one AF with other session.
For PIM from functionality wise both v4 and v6 does same, other than the IP address will be either v4 or v6. 
IPv6 has more options when it comes to PIM SM with RP and BSR.

It can be kept separate as pimv6 similar to OSPF and group common attributes.
Thanks, that helps.
