### ISSUE TITLE
unicode characters in description

### ISSUE THREAD

**Issue by davemiedema** [openconfig/public#355]
https://github.com/openconfig/public/blob/aab7a5ccb91791a40a75fd113fbd798e9060f013/release/models/optical-transport/openconfig-terminal-device.yang#L298

what looks to be a dash in this line is actually a unicode character causing problems in some toolchains.

The comma in this line is also unicode?

https://github.com/openconfig/public/blob/aab7a5ccb91791a40a75fd113fbd798e9060f013/release/models/optical-transport/openconfig-transport-line-protection.yang#L512

**Comment by exa-arrcus** [comment]
I would argue this is a problem with the toolchain not correctly handling unicode characters rather.  The first case is valid unicode u2013 while the second is uFF0C.  The description statement in the ABNF uses the string built in type which legally allows unicode so the toolchain is going to have to handle this for all string types (or derivatives of)

**Comment by chrisy** [comment]
I agree with @exa-arrcus that the tool chain should not break on this. Characterizing these as garbage or non-printable is obviously flawed - I can see them in the pasted text - and any tool chain that balks at Unicode these days should be considered obsolete.

That said, we should endeavor to clean these up, since these specific characters are clearly not intentional.

**Comment by davemiedema** [comment]
fair enough.  edited to reflect that is not garbage but unicode.

**Comment by matt-arrcus** [comment]
One could argue that the “en dash” character was intentional, and its use here is consistent with some grammatical style guides, as a substitute for a comma or for a rhetorical pause.  The spaces before and after help to enforce this possibility.

https://en.wikipedia.org/wiki/Dash#En_dash
