### ISSUE TITLE
top-level mandatory objects are not allowed

### ISSUE THREAD

**Issue by missaesasaya** [openconfig/public#391]
I am using OpenYuma netconf server and when starting the server loading OpenConfig yang files I get the following error:
```
Error: top-level bgp 'NP container' is mandatory
openconfig-bgp.yang:186.3: error(384): top-level mandatory objects are not allowed
Error: 'openconfig-network-instance.yang' import of module 'openconfig-bgp' failed
```
The problem is that the `/bgp/config/as` leaf is mandatory, which makes the top-level container bgp mandatory.

I can work around the error by asking the server not to check this at startup, but it seems that the OpenConfig model is violating best practices in yang design.

**Comment by chrisy** [comment]
How old is your model? There is no `/bgp/config` path in the current model.

**Comment by missaesasaya** [comment]
Sorry, I wrote the wrong path. It is /bgp/global/config/as.

Em qui, 19 de nov de 2020 20:10, Chris Luke <notifications@github.com>
escreveu:

**Comment by bclaise** [comment]
Also reported by pyang --lint
See https://yangcatalog.org/results/openconfig-bgp@2019-07-10_openconfig.html

**Comment by chrisy** [comment]
Yes, and a literal reading of 6020 suggests these errors are correct behavior, though I can't help feeling this makes `mandatory` basically useless. In any case, I'll add it to the agenda for the next operators call which won't be until after US Thanksgiving.

**Comment by robshakir** [comment]
I think that it generally does make `mandatory` meaningless. In general, I feel like the restrictions around data tree presence of nodes (e.g., through `when` and `must`) are poorly expressed in YANG/XPATH (since this really requires the complexity of having an XPath interpreter that is able to work with whatever in-memory representation of the data tree one has). 

Equally, OpenConfig models have generally only added extremely basic validation of data tree contents (e.g., this leaf is only valid when another mode leaf is set to `X`). There are likely plenty of other leaves that *could* have more validation - but don't (e.g., we could be adding `mandatory` in a lot more places).

I'd propose that we just remove this `mandatory` and declare that `mandatory` is not allowed in OC models in the style guide.

**Comment by earies** [comment]
@robshakir +1 - strictly speaking, this leaf (`.../bgp/global/config/as`) has been problematic and very likely to find deviations from various implementations where a "global as" is generally meant to exist at a system level (or DEFAULT_INSTANCE) only.  The use of mandatory within network-instance subdomains don't always apply to non-default instances.

**Comment by chrisy** [comment]
+1 to removing here. We have about a dozen other `mandatory true` statements to examine if we do disallow it.

**Comment by denicola2** [comment]
Hello - We are using Yuma netconf server as well and now integrating bgp to our solution. Similarly, is causing an issue for us:

```
Starting netconfd-pro...
Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
Copyright (c) 2012-2020, YumaWorks, Inc., All Rights Reserved.

openconfig-bgp-types.yang:72.3: warning(1054): Revision date has already been used

Error: top-level NP container 'bgp' is mandatory
openconfig-bgp.yang:186.3: error(384): top-level mandatory objects are not allowed

openconfig-rib-bgp-attributes.yang: line 868: warning(1052): XPath compare value invalid for YANG type

openconfig-rib-bgp-attributes.yang: line 897: warning(1052): XPath compare value invalid for YANG type
```

**Comment by missaesasaya** [comment]
This has been solved by removing the top-level /bgp container, as BGP is now handled inside network-instances. Once the mandatory leaf is inside a list, it is no longer a problem.
