### ISSUE TITLE
Create oc-extension for more succinct and less error prone string validation constraints

### ISSUE THREAD

**Issue by jbemmel** [openconfig/public#455]
In light of some recent bugs found in complex regular expressions for route-distinguishers and extended communities, I'd like to ask if it could make sense to introduce an oc-extension to define more easily verifiable string format constraints.

In PR https://github.com/openconfig/public/pull/453 there are several corrections for route-distinguisher patterns.

As already commented in the Yang file, conceptually the allowed formats are simply a concatenation of 2 numbers or a number and an IP address. Consider the following:
```
oc-ext:string-pattern "<0-4294967295>:<0-65535>"
```
The corresponding regular expression can be auto-derived if needed, but as a formal specification of data model attributes, this is more readable and maintainable.

**Comment by robshakir** [comment]
Thanks for this suggestion. We actually implemented something similar
upstream. @wenovus can provide some details if you're interested.

**Comment by wenovus** [comment]
Thanks for the suggestion, upstream we have a change to auto-generate the regex ranges using a popular library instead of manually writing them. I believe this is the source of these bugs. I've added the tests you mentioned in #453 and they pass in the upstream change.

I didn't think auto-deriving these was worth the effort since we can just add a comment for these regexes, and they're infrequently changed once correctly generated. So given these considerations I think we can do without the extension. Hopefully we can get the changes to openconfig/public soon, I'll update this bug once that happens.

**Comment by jbemmel** [comment]
Makes sense, agree it's a one-time fix and not frequently used
