### ISSUE TITLE
Incorrect default value for leaf unnumbered  in openconfig-interfaces.yang

### ISSUE THREAD

**Issue by qzhengyy** [openconfig/public#5]
Hi,

  leaf unnumbered (in the grouping subinterfaces-config) is referring to "/interfaces/subinterfaces/index", which is referring to 
"/interfaces/subinterfaces/config/index", which is a leaf of type uint32.

leaf unnumbered has a default value "false", and it doesn't fit to uint32

Just wondering, do have any tools to validate the YANG models you published?

Thanks
Qing

**Comment by aashaikh** [comment]
Yep, this is a bug -- thanks for the catch.  The unnumbered leaf was a boolean leaf in a previous version and the default value didn't get updated when we changed the type.  this will be fixed in the next revision of the interfaces model, which we expect to push soon.

As for validation, we rely on pyang for compiling/validating the models, and actual operator usage in NMSes to further test and evaluate the models.  I expect that the unnumbered leaf hasn't been used much in generating configs so far so wasn't caught before.
