### ISSUE TITLE
Creating L2 subinterfaces using oc-if model

### ISSUE THREAD

**Issue by prabjosh** [openconfig/public#538]
Hi team,

On devices running Cisco IOS-XR, subinterfaces can be created either in L2 or L3 mode, depending on the mode supplied in the native CLI or YANG query. The type of vlan encapsulations that can be applied over both can also differ. For example list and range type of vlan encapsulations is only supported over L2 subinterfaces.

But in oc-if:interfaces/interface/subinterfaces/subinterface/config container there is no leaf that defines if the subinterface needs to be created in L2 or L3 mode.

Can you please tell what is the expected behaviour in this case, or if a leaf can be defined in openconfig-interfaces model that can help us make this distinction.

Thank You.
Regards,
Prabhakar

**Comment by prabjosh** [comment]
Gentle Reminder.
Can someone please provide some info?

**Comment by dplore** [comment]
Hi @prabjosh can you investigate how other vendors handle this scenario?  This will help resolve how this functionality can be added in the most vendor neutral way possible.

**Comment by sulrich** [comment]
fwiw, this is a pretty mixed bag across implementations.  some high-level
observations to hopefully get the conversation rolling.

anecdotally, _most_ implementations seem to bias the _default_ configuration of
a subinterface in the direction of making it a layer 3 subinterface. which isn't
to say that there isn't utility in providing a leaf indicating the type of
subinterface to be configured.

to wit ...
- in junos, absent the presence of the `flexible-ethernet-services` or
  `extended-vlan-bridge` configuration in junos an operator cannot configure
  different subinterfaces to support L2 vs. L3. there are a number of different
  models for ethernet service configuration in junos, but anything L2 specific
  with the interface-specific localization of VLANs requires additional
  configuration.
- Arista EOS allows the commingling of L2 and L3 subinterface on a physical
  interface.  this is constrained to platforms that support this functionality
  and requires additional configuration to specify the forwarding VLAN
  associated with the given L2 subinterface. [2]
- IOS-XE (and IOS classic, iirc) has support for the concept of service
  instances or EFPs.  these require an entirely different configuration model
  and provide sufficient tag manipulation functionality to make the most ardent
  ATM aficionado feel right at home. but alas, are not commingled with L3
  subinterfaces. [3]
- to my best recollection NXOS does not have a notion of a separate L2
  subinterface type.  only L3 subinterfaces are supported.  (i cannot find a
  pointer indicating otherwise.)

### references

1.  [Flexible Ethernet Services Encapsulation | Junos OS | Juniper Networks](https://www.juniper.net/documentation/us/en/software/junos/interfaces-ethernet-switches/topics/topic-map/switches-interface-flexible.html)
2. [Arista EOS Central - L2 Sub-interfaces](https://eos.arista.com/eos-4-21-1f/l2-sub-interfaces/)
3. [Carrier Ethernet Configuration Guide, Cisco IOS XE Gibraltar 16.12.x - Configuring Ethernet Virtual Connections on the Cisco ASR 1000 Series Router \[Cisco IOS XE 16\] - Cisco](https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/cether/configuration/xe-16-12/ce-xe-16-12-book/m_ce-ether-vc-infra-xe.html)

**Comment by dplore** [comment]
Thanks @sulrich this helps provide some background, but I am not sure how help @prabjosh yet.  @prabjosh , can you provide a use case of something you want to configure that is not clear in openconfig?
