### ISSUE TITLE
AFT Yang model missing 'uses aft-top' statement

### ISSUE THREAD

**Issue by vikram-arrcus** [openconfig/public#64]
Diff from local changes, required to fix yang file issue

diff --git a/openconfig-aft.yang b/openconfig-aft.yang
index 3d7f52b..2e80363 100644
--- a/openconfig-aft.yang
+++ b/openconfig-aft.yang
@@ -442,4 +442,5 @@ module openconfig-aft {
       }
     }
   }
+uses aft-top;
 }

**Comment by robshakir** [comment]
The AFT model is instantiated inside the network instance model (at `/network-instances/network-instance/afts` - this is to provide the ability to have per-VRF AFTs.

**Comment by robshakir** [comment]
We don't propose to change this at this point since it results in duplication of where the data model is rooted (assuming that both `network-instance` and `aft` are built). We can potentially re-examine this if there is a specific use case.

Closing this issue for the moment, please re-open it with additional details of the use case and we can consider this.
