### ISSUE TITLE
platform:location not shown in ops.openconfig.net web viewers

### ISSUE THREAD

**Issue by osquitun** [openconfig/public#644]
The openconfig-platform:components/component/state/location leaf is not displayed in:
http://ops.openconfig.net/branches/models/OC/openconfig-platform.html#
http://ops.openconfig.net/branches/models/OC/docs/openconfig-platform.html

while still included on line 342 of
https://github.com/openconfig/public/blob/master/release/models/platform/openconfig-platform.yang

Is location still intended to be included as system supplied description of location of the component?

**Comment by dplore** [comment]
Yes, location is still intended.  The ops.openconfig.net website is pointing to the private 'models' repository instead of the 'public' repository.  The private 'model' repository is no longer maintained and becoming stale.  We need to update the ops.openconfig website to use public.  Apologies for the inconvenience!
