### ISSUE TITLE
openconfig-pf-forwarding-policies.yang broken

### ISSUE THREAD

**Issue by dbarrosop** [openconfig/public#66]
Hello,
so this problem was found by @ktbyers while trying to compile some models with `pyangbind` for `napalm-yang`. The problem is that the module `openconfig-pf-forwarding-policies` references the grouping `oc-pmatch:ip-protocol-fields-top ` here:

https://github.com/openconfig/public/blob/master/release/models/policy-forwarding/openconfig-pf-forwarding-policies.yang#L111

But looks like there was a refactoring recently in the `openconfig-pf-forwarding-policies` module that didn't take this usage into account. The commit in questions is this one:

https://github.com/openconfig/public/commit/3478fc2421ab3c725add275078558166e8c177f7#diff-220fd12c22cbb377b2d1b9e546fae8b0L176

Regards
David

**Comment by aashaikh** [comment]
hi David, thanks for pointing this out (and thanks @ktbyers).  This is a known issue which we'll get resolved shortly. 

We did indeed refactor the ACL (and it's packet-match module) which affected policy-forwarding and AFT models -- we were holding off publishing the latter due to some potential pending changes, but that delay created this problem.  Appreciate your patience.

**Comment by robshakir** [comment]
This has now been fixed - the head of master should now build across these modules. We're working on extending internal CI to our release process.
