### ISSUE TITLE
Prefix for import of openconfig-inet-types

### ISSUE THREAD

**Issue by ankitjain093** [openconfig/public#69]
For consistency, can we have the prefix oc-inet for the import of openconfig-inet-types in openconfig-mpls-*.yang files: 

```javascript
- import openconfig-inet-types { prefix inet; }
+ import openconfig-inet-types { prefix oc-inet; }
```

**Comment by robshakir** [comment]
Hi,

Is there a reason other than aesthetic we should make this change please?

Thanks,
r.

**Comment by ankitjain093** [comment]
Hi

The prefix defined in openconfig-inet-types.yang is oc-inet.
https://github.com/openconfig/public/blob/master/release/models/types/openconfig-inet-types.yang

Also, the 'inet' prefix is associated with ietf-inet-types.yang.


Thank You.

Regards
Ankit

**Comment by robshakir** [comment]
There is no need for unique prefixes across all YANG modules, or for the prefix to match. I recommend working with your tooling developer to fix these issues.

Thanks,
r.

**Comment by martin-volf** [comment]
I understand there is no intention to change anything here, nevertheless I'd like to add my comments:
 * first, even if there were only purely aesthetic reasons, it still should not be discarded just because of that
 * second, it is not the case - `inet:ip-prefix` is immediately read as "the `ip-prefix` type from `ietf-inet-types`" by virtually anyone (or at least anyone not from the OpenConfig team), which leads to quite some confusion and possibly errors.

By the way, what is the reasoning behind the decision to discard `ietf-inet-types` and replace it with `openconfig-inet-types`?

Thanks,
Martin
