### ISSUE TITLE
Should network-instance type be mandatory?

### ISSUE THREAD

**Issue by dplore** [openconfig/public#726]
network-instance type is currently optional and has no default.  When configuring a network instance, it is currently ambiguous as to which type a network operating system (NOS) will use.  

It seems network-instance type should be mandatory in order to get deterministic behavior.  Modifying the current leaf would be a breaking change.

Model Reference:
https://github.com/openconfig/public/blob/f3f05d5f6e38ca7c46671ea5a4c11b62d264c10b/release/models/network-instance/openconfig-network-instance.yang#L1193-L1208

featureprofiles test which exposed this issue:
https://github.com/openconfig/featureprofiles/pull/624

**Comment by robshakir** [comment]
We have generally not used mandatory markings in the models. I believe
there is one instance of it - since there was discussion as to whether this
could be consistently done across implementations, and further discussions
around the lack of presence containers in OpenConfig.

Before adding this specifically can we make sure we think about cross model
consistency please?

r.

**Comment by earies** [comment]
There are currently 17 instances of `mandatory=true` across the OC model set

The looseness of OC models by not implementing stricter checks and relationships is a double-edged sword.  The looser the model, the more precise specifications will need to be in order to give implementation guidance and consistency.  Without this you can expect implementation differences across the board.

For this case, since `type` is optional, we have undefined behavior as a result (There are many other cases of this as well).  This is currently being triggered by way of ONDATRA tests that assume some level of pre-configuration but is not limited to such.

An implementation can always produce a deviation, make this mandatory on the server (or handle purely internal) but this should be covered in a spec at minimum.  Having it directly encoded in the YANG model means tooling can understand this whereas all side channel specification guidance needs to be manually codified with a constant understanding of spec iteration.

What do we think the harm is in making this leaf mandatory since in theory it already is?
