### ISSUE TITLE
Allow user-defined ASns in BGP's repeat-n

### ISSUE THREAD

**Issue by lamehost** [openconfig/public#76]
I suggest to extend BGP's repeat-n to support user-defined ASns.
Options should be:
 - LAST: Replicate current behavior
 - uint32: Replicate current behavior but uses user defined ASn instead of last

```
  grouping as-path-prepend-config {
    description
      "Configuration data for the AS path prepend action";

    leaf repeat-n {
      type uint8 {
        range 1..max;
      }
      description
        "Number of times to prepend the local AS number to the AS
        path.  The value should be between 1 and the maximum
        supported by the implementation.";
    }

    leaf options {
      type uint32;
      type enumeration {
        enum LAST {
          description
            "The leftmost ASn in the path";
        }
      }
      description
        "Indicates the ASn prepended to the PATH.";
    }
  }
```

Reason is with current model you cannot use prepend with self-originated prefixes like those redistribute to BGP from connected or static.

**Comment by aashaikh** [comment]
Thanks for the feedback -- this requirement came up from other operators as well and we've added support for it.  The updated BGP / policy model will have support to specify the ASN that is prepended (using a separate leaf rather than the structure proposed here).  We hope to push out the new version that includes a few other fixes / features later this week.
