### ISSUE TITLE
Auto-negotiate is not a valid value in openconfig-interfaces

### ISSUE THREAD

**Issue by leopivat** [openconfig/public#769]
Hello,

I'm trying to configure a Cisco interface in auto negotiation. I can already modify the speed to 10mb, 100mb, 1gb... and the duplex half and full. But I can't find how to put in auto (like in the cisco interface configuration write `duplex auto` and `speed auto`) To put duplex in auto I delete the value here `/restconf/data/openconfig-interfaces:interfaces/interface=GigabitEthernet1%2F0%2F1/ethernet/config/duplex-mode` but for the speed I can't figure how to do it. I try to delete it too but i have an error message `"error-message": "/oc-if:interfaces/interface{GigabitEthernet1/0/1}/oc-eth:ethernet/config/port-speed: function_clause"`

 I can't delete `port-speed` and if I request an interface in auto negotiation mode I have `"openconfig-if-ethernet:port-speed": "openconfig-if-ethernet:auto-negotiate"`.

So I try to PATCH the value like `SPEED_1GB` by `auto-negotiate` but it's not a valid value. I have already seen in the documentation it's not a valid value like SPEED_10MB, SPEED_100MB...

So how could I manage to return in auto-negotiate mode ? Also I have seen `auto-negotiate` is set to False for every interface and I can't set it to True.

Thank you for taking time to read me.

**Comment by dplore** [comment]
Seems like a bug in Cisco?   You could open a bug with them.  Here's the prescribed behavior for port speed when using auto-negotiate.
 https://github.com/openconfig/public/blob/ce95d0f03e85450308ebd42e544a7447d78eae85/release/models/interfaces/openconfig-if-ethernet.yang#L347-L359

If I am missing the problem here and  you feel the openconfig model needs changes, please feel free to reopen.
