### ISSUE TITLE
Use of prefix "inet" by both both ietf-inet-types and openconfig-inet-types creates a problem.

### ISSUE THREAD

**Issue by mjethanandani** [openconfig/public#79]
openconfig-isis module imports ietf-inet-types with a prefix of inet. openconfig-isis also includes openconfig-isis-lsp which imports openconfig-inet-types with a prefix inet. Thus the module openconfig-isis has two modules using the same prefix, which controllers will have a problem resolving.

Suggest that openconfig-isis-lsp use openconfig-inet-types with a prefix like oc-inet to de-duplicate the prefix.

**Comment by robshakir** [comment]
According to RFC6020, this shouldn't be an issue. Imported modules are scoped according to the module or submodule that they are imported in, therefore it should not be the case that any tooling ends up with the scenario that it can resolve `inet` to `ietf-inet-types` in `openconfig-isis-lsp`, since `openconfig-isis` imports should not be available there. I recommend fixing this in the toolchain that you're using.

That being said, we'll address this for the sake of consistency such that `inet` is used in `openconfig-isis` to mean `openconfig-inet-types` as part of the wider move away from IETF modules.
