### ISSUE TITLE
openconfig-if-aggregate.yang: Request to add leafs and notification.

### ISSUE THREAD

**Issue by sushant-kumar** [openconfig/public#8]
Hi,

This is an enhancement request to add following leafs in the "openconfig-if-aggregate.yang" module -
1. port-num
2. partner-port-num
3. mux-state
4. notification lacp-mux-state-change.

The latest YANG model is edited with these suggestions and attached with this Issue report.

**Attachments**:
1. Enhanced YANG model "openconfig-if-aggregate.yang"
[openconfig-if-aggregate.yang.txt](https://github.com/openconfig/public/files/130487/openconfig-if-aggregate.yang.txt)
2. Diff of proposed enhanced model with the latest existing model.
[enhancement-diff.yang.txt](https://github.com/openconfig/public/files/130489/enhancement-diff.yang.txt)

Regards,
Sushant

**Comment by robshakir** [comment]
Hi Sushant,

Thanks for raising this issue.

Please note, we do not accept pull requests/direct contributions through this repository. As per the comments in the README.md documents in this repository the features that are included in OpenConfig models are shaped based on the operational use cases of the operators that participate in the project. As of yet, these leaves have not been a requirement raised.

Additionally, currently, OpenConfig does not define YANG notifications - in some respects, this is because such notifications can be directly achieved for any path through the use of the subscription-based streaming telemetry defined in the OpenConfig protocol RPC description module.

We will discuss whether there is operator interest in including these leaves, and if so, they may be added in a future revision of the module. If not, I would encourage you to either:

* (If you are working for a network operator, and can agree to the points in 'What do I need to do to join OpenConfig?' in the [FAQ](http://www.openconfig.net/documents/faq-for-operators)) Subscribe to the OpenConfig-ops list, and describe your use case for these leaves.
* (If you are working for a vendor) Augment the model with these leaves in your implementation.

I'll close this issue for the moment, pending one of the actions above.

Kind regards,
r.
