### ISSUE TITLE
Secondary IPv4 addresses

### ISSUE THREAD

**Issue by dbarrosop** [openconfig/public#88]
Some "industry standard" devices require a `secondary` option when configuring multiple IPv4 addresses. For instance:

```
interface Lo0
   ip address 192.168.1.1/32
   ip address 192.168.1.2/32 secondary
   ip address 192.168.1.3/32 secondary
```

I extended the model in my project to workaround the lack of it in the OC model but it would be nice to if it could be fixed here.

For reference: https://github.com/napalm-automation/napalm-yang/blob/develop/yang_napalm/interfaces/napalm-if-ip.yang

**Comment by aashaikh** [comment]
Hi David, thanks for the comment.  We've discussed this a few times in the past but so far resisted adding a primary/secondary designation to interface IP addresses, primarily because we considered it too tied to one particular "industry standard".   In our configs we've typically just used the first address in the list to be primary if we need to map to a particular vendor impl.

In any case, I'll add a discussion item on this for discussion with the operator group to see if we want to revisit based on your feedback.

**Comment by robshakir** [comment]
One thing that we could do here which might result in not having the specific `secondary` or `primary` flag is to make the `address` list `ordered-by user` such that the ordering is deterministic and the primary address can be distinguished based on this order for mapping to CLI.

**Comment by dbarrosop** [comment]
I agree that it is too tied to a particular implementation, problem is that implementation has been replicated everywhere so AFAICT most DC NOS, with the exception of Junos, requires that keyword. 

Let me know what you decide and I will see how to proceed.

Thanks!

**Comment by sunseawq** [comment]
Any update to this primary /secondary support? Has Rob's proposal been accepted?

**Comment by dplore** [comment]
https://github.com/openconfig/public/pull/872 resolves this issue
