### ISSUE TITLE
QoS models revision statements in wrong order

### ISSUE THREAD

**Issue by missaesasaya** [openconfig/public#975]
The recent commit in SHA1 9b3eed1f1ede0824e9a3af42d7f7ccb52d75c127 has caused the following warnings with pyang:

./qos/openconfig-qos-elements.yang:46: warning: the revision statements are not given in reverse chronological order
./qos/openconfig-qos-interfaces.yang:36: warning: the revision statements are not given in reverse chronological order
./qos/openconfig-qos-mem-mgmt.yang:40: warning: the revision statements are not given in reverse chronological order
./qos/openconfig-qos.yang:38: warning: the revision statements are not given in reverse chronological order

**Comment by dplore** [comment]
@wenovus I guess we are missing CI coverage for in-order chronological revision statements?

**Comment by wenovus** [comment]
> @wenovus I guess we are missing CI coverage for in-order chronological revision statements?

Yes previously pyangbind was checking them and I moved it to a compatibility check since it was failing. Now that we have maintainers and the original issue is fixed I can move pyangbind back into the required list of checks and that will catch it.

I'm not sure why only pyangbind checks for it, I'll have to look if we can just enable WARNINGs to gate PRs when running pyang.
